version: "3.9"
services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    env_file:
      - ./.env
    volumes:
      - pgdbdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    command: make entrypoint
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    container_name: celery-worker
    command: make worker
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    container_name: celery-beat
    command: make beat
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379

volumes:
  pgdbdata: null