name: main

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2
        with:
          docker-version: '20.10.7'
          
      - name: Build and run docker
        run: make run
        
      - name: Run tests
        run: make tests

      - name: Run linters
        run: make linters

      - name: Clean up
        run: make clean
